### ISSUE TITLE
Getting Started Tutorial

### ISSUE THREAD

**Issue by shannah** [reportmill/SnapKit#2]
Do you have a getting started tutorial or example "Hello World" with SnapKit?

**Comment by reportmill** [comment]
I'm ashamed to admit I have done almost nothing here. I just added a start of a page to the wiki:

[Getting Started: Hello World UI app](https://github.com/reportmill/SnapKit/wiki/Getting-Started:-Creating-Hello-World-UI)

I will do some more work to update this today. I'm thrilled to have some outside interest!

**Comment by reportmill** [comment]
I added a little bit more info to the HelloWorld - plus a pointer to JavaDoc in the wiki.

**Comment by shannah** [comment]
Thanks.  I really like the concept of SnapKit.  And I'm looking forward to taking it for a spin.
