### ISSUE TITLE
Does it compile to Android and iOS..?

### ISSUE THREAD

**Issue by dwaal** [reportmill/SnapKit#3]
Hi,

great toolkit. It seems simple enough to allow compilation at least to Android. Maybe even iOS. UI toolkits like libGDX's UI toolkit and PlayN's tripleplay can do this. You could copy their approach.

**Comment by reportmill** [comment]
Thanks! I do think SnapKit could easily compile to Android - by design, the only thing that should be needed is a package like the existing snap.swing (or the snaptea project), but for Android (so snap.android). This package would just need to supply the platform interfaces for painting, images, fonts and events. I imaging something could be up and running in a week.

I'm less sure about iOS, though I suppose it would be trivial if you used an existing port like Gluon.

My focus has been exclusively for Win/Mac and the browser, which gets me almost everywhere. I would gladly expand to Android/iOS if there was proper funding. :-)

**Comment by dwaal** [comment]
Kind of a chicken egg problem with the funding. You need unique features to get traction. Once you have traction you can get funding. At the moment SnapKit is nice but not unique. The browser support is a little unique. Android and iOS support combined with a simple usage and small size would be unique and could get traction.

LibGDX and PlayN uses Mobidevelop. Gluon uses Mobidevelop (formerly Robovm) under the hood for iOS support. They are currently switching to GraalVM AOT.

I doubt it is much work to get Android and iOS support. You just need to copy from the projects above. I recommend looking at PlayN first (and talk to its project lead Michael Baine) since it is the least complex of the three. However using GraalVM AOT would be nice too.

**Comment by reportmill** [comment]
You are right about chicken & egg problem. I think SnapKit has a lot to offer and a lot of promise, but I don't have the resources to take it in many different directions. I suppose if I got a lot of feedback about Android/iOS, I might pursue it, but I doubt that will happen. I mostly just build out enough features to satisfy the needs of my own products. :-)

**Comment by eGit** [comment]
I watch SnapKit regularly and evaluated it a while back. With Android and iOS support I would have used it for many projects. Instead I went with libGDX which has a cumbersome UI.

SnapKit could really fill a void and turn into a golden egg with Android and iOS support.

**Comment by dwaal** [comment]
+1

**Comment by konsoletyper** [comment]
BTW, TeaVM supports compilation to C. We already use it to compile CoSpaces (as an experiment, still not for production). C backend for TeaVM is under active development now. It does not support iOS, but supporting iOS just requires implementing few runtime functions. Another problem is support for async functions is quite unstable now (and I know that reportmill uses them extensively). Let me know if you want to try this direction (I'm not sure there's any advantage over RoboVM or Graal AOT), and I'll implement all missing features in TeaVM/C.

**Comment by suthcark** [comment]
Most companies (like Gluon Mobile) use the GPLv3 to keep control over their work: https://gluonhq.com/simplifying-gluon

Most of their code is open source. A tiny part is not and you have to pay for it (and people pay). Still, you can only use the open source parts and it works.

Still, no other company would swoop in and "steal" their work since it is GPLv3, so they would have to open source it themselves.

Also, Gluon at any point can offer different licenses for their GPLv3 stuff if a companies pays them to do it.

**Comment by reportmill** [comment]
I greatly appreciate this interest - I didn't realize anyone even watched this project. I don't mean to be myopic (or protective) with SnapKit - it's just that I'm very engineering focused. I do believe that SnapKit is a diamond in the rough (thanks to TeaVM). But without a motivated backer and/or team, I don't think it can rise to the level of a Codename1 or Vaadin. I've built a bit of software with the hope that customers will find it. I call it the "Field of Dreams" model - and it's only worked out for me once. So I'm scared of spending months exploring Android/iOS until someone convinces me it's worth it (say by paying for those months :-).

I'm also such a huge fan of the browser now. It's so fun to see these apps running so well (and loading so fast) - and they looks great on an iPad and even an Android phone. And without the hassle and expense of an App store.

I also wonder if the Gluon folks would consider adding Swing to their stuff. Seems like it should be easier than JavaFX. Then SnapKit would automatically run. Although I did used to have a version of SnapKit working on JavaFX. It was pretty simple, but the JavaFX Canvas wasn't quite as nice as HTML Canvas (maybe that's changed).

**Comment by wordlessly** [comment]
Are you implementing everything by drawing on a "canvas"? That's what PlayN is doing. Should be a matter of day(s) to look at their source and copy what you need. If you post to the PlayN google group and tell them what you need for implementation they can tell you the technical details of their implementation. https://groups.google.com/forum/#!forum/playn

My guess is, that Android and iOS both have a "canvas/surface" which PlayN hides behind a common interface that PlayN Tripleplay (their UI) requires to work. All super simple and they ironed out the kinks.

**Comment by reportmill** [comment]
It would probably be reasonable to write a SnapKit adapter for PlayN, then leverage their code to get Android/iOS compatibility (or any platform they support). However, it doesn't look like they have much of a community either, judging by the traffic on their GitHub and Google group.
