### ISSUE TITLE
SnapCharts - zoom level is not visible in browser

### ISSUE THREAD

**Issue by GiantCrocodile** [reportmill/SnapKit#6]
Hello,

I just noticed that at the SnapCharts online demo you can't set the zoom level via the dropdown in the corner:

![grafik](https://github.com/user-attachments/assets/d3b7b645-6a3c-4b8f-8c1a-6fd77881a6d3)

The dropdown opens below the visible part of the page and thus you can't read or click it properly. This happens with Firefox 128.

Best Regards,

**Comment by reportmill** [comment]
Thanks for taking the time to report that! I haven't been working much on SnapCharts this year (mostly focused on SnapCode (https://github.com/reportmill/SnapCode).

Do you have an interest in SnapCharts? I would love a good excuse to start making more fixes and enhancements. :-)

**Comment by GiantCrocodile** [comment]
@reportmill Right now I'm using none of your tools nor the framework. I just saw one of your posts somewhere by chance and was impressed that you did it on your own in such a quite short time compared to what you achieved already. So I opened an issue because I found this bug while I tested your demos and I was curious how it will be fixed. I suspect it's a general bug that is not specific to SnapCharts so likely something the UI framework should take care of on its own.

**Comment by reportmill** [comment]
I think I stubbed out this feature - but didn't finish implementing the functionality. Should be quite simple (just need to make a scale call in the top level page paint routine), but I'm going to put this on the shelf for now (I don't think this design app has a real user base yet :-)).
